[package]
name = "rust-things"
version = "0.0.1"
authors = ["Simon Gardling"]

[[bin]]
name = "rust-things"

[profile.dev]
opt-level = 3
lto = "thin"

[profile.release]
opt-level = 3
lto = "thin"

[dependencies]
rayon = "1.5"